
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceProviderCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ServiceProviderCategory
 * 
 */
export type ServiceProviderCategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceProviderCategoryPayload>

export type AggregateServiceProviderCategory = {
  _count: ServiceProviderCategoryCountAggregateOutputType | null
  _min: ServiceProviderCategoryMinAggregateOutputType | null
  _max: ServiceProviderCategoryMaxAggregateOutputType | null
}

export type ServiceProviderCategoryMinAggregateOutputType = {
  id: string | null
  name: string | null
  icon: string | null
  parentId: string | null
  isActive: boolean | null
  isInHome: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ServiceProviderCategoryMaxAggregateOutputType = {
  id: string | null
  name: string | null
  icon: string | null
  parentId: string | null
  isActive: boolean | null
  isInHome: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ServiceProviderCategoryCountAggregateOutputType = {
  id: number
  name: number
  icon: number
  parentId: number
  isActive: number
  isInHome: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ServiceProviderCategoryMinAggregateInputType = {
  id?: true
  name?: true
  icon?: true
  parentId?: true
  isActive?: true
  isInHome?: true
  createdAt?: true
  updatedAt?: true
}

export type ServiceProviderCategoryMaxAggregateInputType = {
  id?: true
  name?: true
  icon?: true
  parentId?: true
  isActive?: true
  isInHome?: true
  createdAt?: true
  updatedAt?: true
}

export type ServiceProviderCategoryCountAggregateInputType = {
  id?: true
  name?: true
  icon?: true
  parentId?: true
  isActive?: true
  isInHome?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ServiceProviderCategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceProviderCategory to aggregate.
   */
  where?: Prisma.ServiceProviderCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceProviderCategories to fetch.
   */
  orderBy?: Prisma.ServiceProviderCategoryOrderByWithRelationInput | Prisma.ServiceProviderCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceProviderCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceProviderCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceProviderCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceProviderCategories
  **/
  _count?: true | ServiceProviderCategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceProviderCategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceProviderCategoryMaxAggregateInputType
}

export type GetServiceProviderCategoryAggregateType<T extends ServiceProviderCategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceProviderCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceProviderCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceProviderCategory[P]>
}




export type ServiceProviderCategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceProviderCategoryWhereInput
  orderBy?: Prisma.ServiceProviderCategoryOrderByWithAggregationInput | Prisma.ServiceProviderCategoryOrderByWithAggregationInput[]
  by: Prisma.ServiceProviderCategoryScalarFieldEnum[] | Prisma.ServiceProviderCategoryScalarFieldEnum
  having?: Prisma.ServiceProviderCategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceProviderCategoryCountAggregateInputType | true
  _min?: ServiceProviderCategoryMinAggregateInputType
  _max?: ServiceProviderCategoryMaxAggregateInputType
}

export type ServiceProviderCategoryGroupByOutputType = {
  id: string
  name: string
  icon: string
  parentId: string | null
  isActive: boolean
  isInHome: boolean
  createdAt: Date
  updatedAt: Date
  _count: ServiceProviderCategoryCountAggregateOutputType | null
  _min: ServiceProviderCategoryMinAggregateOutputType | null
  _max: ServiceProviderCategoryMaxAggregateOutputType | null
}

type GetServiceProviderCategoryGroupByPayload<T extends ServiceProviderCategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceProviderCategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceProviderCategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceProviderCategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceProviderCategoryGroupByOutputType[P]>
      }
    >
  >



export type ServiceProviderCategoryWhereInput = {
  AND?: Prisma.ServiceProviderCategoryWhereInput | Prisma.ServiceProviderCategoryWhereInput[]
  OR?: Prisma.ServiceProviderCategoryWhereInput[]
  NOT?: Prisma.ServiceProviderCategoryWhereInput | Prisma.ServiceProviderCategoryWhereInput[]
  id?: Prisma.UuidFilter<"ServiceProviderCategory"> | string
  name?: Prisma.StringFilter<"ServiceProviderCategory"> | string
  icon?: Prisma.StringFilter<"ServiceProviderCategory"> | string
  parentId?: Prisma.UuidNullableFilter<"ServiceProviderCategory"> | string | null
  isActive?: Prisma.BoolFilter<"ServiceProviderCategory"> | boolean
  isInHome?: Prisma.BoolFilter<"ServiceProviderCategory"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ServiceProviderCategory"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceProviderCategory"> | Date | string
  parent?: Prisma.XOR<Prisma.ServiceProviderCategoryNullableScalarRelationFilter, Prisma.ServiceProviderCategoryWhereInput> | null
  children?: Prisma.ServiceProviderCategoryListRelationFilter
}

export type ServiceProviderCategoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isInHome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  parent?: Prisma.ServiceProviderCategoryOrderByWithRelationInput
  children?: Prisma.ServiceProviderCategoryOrderByRelationAggregateInput
}

export type ServiceProviderCategoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ServiceProviderCategoryWhereInput | Prisma.ServiceProviderCategoryWhereInput[]
  OR?: Prisma.ServiceProviderCategoryWhereInput[]
  NOT?: Prisma.ServiceProviderCategoryWhereInput | Prisma.ServiceProviderCategoryWhereInput[]
  name?: Prisma.StringFilter<"ServiceProviderCategory"> | string
  icon?: Prisma.StringFilter<"ServiceProviderCategory"> | string
  parentId?: Prisma.UuidNullableFilter<"ServiceProviderCategory"> | string | null
  isActive?: Prisma.BoolFilter<"ServiceProviderCategory"> | boolean
  isInHome?: Prisma.BoolFilter<"ServiceProviderCategory"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ServiceProviderCategory"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceProviderCategory"> | Date | string
  parent?: Prisma.XOR<Prisma.ServiceProviderCategoryNullableScalarRelationFilter, Prisma.ServiceProviderCategoryWhereInput> | null
  children?: Prisma.ServiceProviderCategoryListRelationFilter
}, "id">

export type ServiceProviderCategoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isInHome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ServiceProviderCategoryCountOrderByAggregateInput
  _max?: Prisma.ServiceProviderCategoryMaxOrderByAggregateInput
  _min?: Prisma.ServiceProviderCategoryMinOrderByAggregateInput
}

export type ServiceProviderCategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceProviderCategoryScalarWhereWithAggregatesInput | Prisma.ServiceProviderCategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceProviderCategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceProviderCategoryScalarWhereWithAggregatesInput | Prisma.ServiceProviderCategoryScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"ServiceProviderCategory"> | string
  name?: Prisma.StringWithAggregatesFilter<"ServiceProviderCategory"> | string
  icon?: Prisma.StringWithAggregatesFilter<"ServiceProviderCategory"> | string
  parentId?: Prisma.UuidNullableWithAggregatesFilter<"ServiceProviderCategory"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"ServiceProviderCategory"> | boolean
  isInHome?: Prisma.BoolWithAggregatesFilter<"ServiceProviderCategory"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceProviderCategory"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceProviderCategory"> | Date | string
}

export type ServiceProviderCategoryCreateInput = {
  id?: string
  name: string
  icon: string
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.ServiceProviderCategoryCreateNestedOneWithoutChildrenInput
  children?: Prisma.ServiceProviderCategoryCreateNestedManyWithoutParentInput
}

export type ServiceProviderCategoryUncheckedCreateInput = {
  id?: string
  name: string
  icon: string
  parentId?: string | null
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.ServiceProviderCategoryUncheckedCreateNestedManyWithoutParentInput
}

export type ServiceProviderCategoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.ServiceProviderCategoryUpdateOneWithoutChildrenNestedInput
  children?: Prisma.ServiceProviderCategoryUpdateManyWithoutParentNestedInput
}

export type ServiceProviderCategoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.ServiceProviderCategoryUncheckedUpdateManyWithoutParentNestedInput
}

export type ServiceProviderCategoryCreateManyInput = {
  id?: string
  name: string
  icon: string
  parentId?: string | null
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceProviderCategoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceProviderCategoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceProviderCategoryNullableScalarRelationFilter = {
  is?: Prisma.ServiceProviderCategoryWhereInput | null
  isNot?: Prisma.ServiceProviderCategoryWhereInput | null
}

export type ServiceProviderCategoryListRelationFilter = {
  every?: Prisma.ServiceProviderCategoryWhereInput
  some?: Prisma.ServiceProviderCategoryWhereInput
  none?: Prisma.ServiceProviderCategoryWhereInput
}

export type ServiceProviderCategoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceProviderCategoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isInHome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceProviderCategoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isInHome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceProviderCategoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  icon?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isInHome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ServiceProviderCategoryCreateNestedOneWithoutChildrenInput = {
  create?: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutChildrenInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.ServiceProviderCategoryCreateOrConnectWithoutChildrenInput
  connect?: Prisma.ServiceProviderCategoryWhereUniqueInput
}

export type ServiceProviderCategoryCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput> | Prisma.ServiceProviderCategoryCreateWithoutParentInput[] | Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput | Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.ServiceProviderCategoryCreateManyParentInputEnvelope
  connect?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
}

export type ServiceProviderCategoryUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput> | Prisma.ServiceProviderCategoryCreateWithoutParentInput[] | Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput | Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.ServiceProviderCategoryCreateManyParentInputEnvelope
  connect?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ServiceProviderCategoryUpdateOneWithoutChildrenNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutChildrenInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.ServiceProviderCategoryCreateOrConnectWithoutChildrenInput
  upsert?: Prisma.ServiceProviderCategoryUpsertWithoutChildrenInput
  disconnect?: Prisma.ServiceProviderCategoryWhereInput | boolean
  delete?: Prisma.ServiceProviderCategoryWhereInput | boolean
  connect?: Prisma.ServiceProviderCategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceProviderCategoryUpdateToOneWithWhereWithoutChildrenInput, Prisma.ServiceProviderCategoryUpdateWithoutChildrenInput>, Prisma.ServiceProviderCategoryUncheckedUpdateWithoutChildrenInput>
}

export type ServiceProviderCategoryUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput> | Prisma.ServiceProviderCategoryCreateWithoutParentInput[] | Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput | Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.ServiceProviderCategoryUpsertWithWhereUniqueWithoutParentInput | Prisma.ServiceProviderCategoryUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.ServiceProviderCategoryCreateManyParentInputEnvelope
  set?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  disconnect?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  delete?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  connect?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  update?: Prisma.ServiceProviderCategoryUpdateWithWhereUniqueWithoutParentInput | Prisma.ServiceProviderCategoryUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.ServiceProviderCategoryUpdateManyWithWhereWithoutParentInput | Prisma.ServiceProviderCategoryUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.ServiceProviderCategoryScalarWhereInput | Prisma.ServiceProviderCategoryScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type ServiceProviderCategoryUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput> | Prisma.ServiceProviderCategoryCreateWithoutParentInput[] | Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput | Prisma.ServiceProviderCategoryCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.ServiceProviderCategoryUpsertWithWhereUniqueWithoutParentInput | Prisma.ServiceProviderCategoryUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.ServiceProviderCategoryCreateManyParentInputEnvelope
  set?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  disconnect?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  delete?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  connect?: Prisma.ServiceProviderCategoryWhereUniqueInput | Prisma.ServiceProviderCategoryWhereUniqueInput[]
  update?: Prisma.ServiceProviderCategoryUpdateWithWhereUniqueWithoutParentInput | Prisma.ServiceProviderCategoryUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.ServiceProviderCategoryUpdateManyWithWhereWithoutParentInput | Prisma.ServiceProviderCategoryUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.ServiceProviderCategoryScalarWhereInput | Prisma.ServiceProviderCategoryScalarWhereInput[]
}

export type ServiceProviderCategoryCreateWithoutChildrenInput = {
  id?: string
  name: string
  icon: string
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.ServiceProviderCategoryCreateNestedOneWithoutChildrenInput
}

export type ServiceProviderCategoryUncheckedCreateWithoutChildrenInput = {
  id?: string
  name: string
  icon: string
  parentId?: string | null
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceProviderCategoryCreateOrConnectWithoutChildrenInput = {
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutChildrenInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutChildrenInput>
}

export type ServiceProviderCategoryCreateWithoutParentInput = {
  id?: string
  name: string
  icon: string
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.ServiceProviderCategoryCreateNestedManyWithoutParentInput
}

export type ServiceProviderCategoryUncheckedCreateWithoutParentInput = {
  id?: string
  name: string
  icon: string
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.ServiceProviderCategoryUncheckedCreateNestedManyWithoutParentInput
}

export type ServiceProviderCategoryCreateOrConnectWithoutParentInput = {
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput>
}

export type ServiceProviderCategoryCreateManyParentInputEnvelope = {
  data: Prisma.ServiceProviderCategoryCreateManyParentInput | Prisma.ServiceProviderCategoryCreateManyParentInput[]
  skipDuplicates?: boolean
}

export type ServiceProviderCategoryUpsertWithoutChildrenInput = {
  update: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateWithoutChildrenInput, Prisma.ServiceProviderCategoryUncheckedUpdateWithoutChildrenInput>
  create: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutChildrenInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutChildrenInput>
  where?: Prisma.ServiceProviderCategoryWhereInput
}

export type ServiceProviderCategoryUpdateToOneWithWhereWithoutChildrenInput = {
  where?: Prisma.ServiceProviderCategoryWhereInput
  data: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateWithoutChildrenInput, Prisma.ServiceProviderCategoryUncheckedUpdateWithoutChildrenInput>
}

export type ServiceProviderCategoryUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.ServiceProviderCategoryUpdateOneWithoutChildrenNestedInput
}

export type ServiceProviderCategoryUncheckedUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceProviderCategoryUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.ServiceProviderCategoryCreateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedCreateWithoutParentInput>
}

export type ServiceProviderCategoryUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateWithoutParentInput, Prisma.ServiceProviderCategoryUncheckedUpdateWithoutParentInput>
}

export type ServiceProviderCategoryUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.ServiceProviderCategoryScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateManyMutationInput, Prisma.ServiceProviderCategoryUncheckedUpdateManyWithoutParentInput>
}

export type ServiceProviderCategoryScalarWhereInput = {
  AND?: Prisma.ServiceProviderCategoryScalarWhereInput | Prisma.ServiceProviderCategoryScalarWhereInput[]
  OR?: Prisma.ServiceProviderCategoryScalarWhereInput[]
  NOT?: Prisma.ServiceProviderCategoryScalarWhereInput | Prisma.ServiceProviderCategoryScalarWhereInput[]
  id?: Prisma.UuidFilter<"ServiceProviderCategory"> | string
  name?: Prisma.StringFilter<"ServiceProviderCategory"> | string
  icon?: Prisma.StringFilter<"ServiceProviderCategory"> | string
  parentId?: Prisma.UuidNullableFilter<"ServiceProviderCategory"> | string | null
  isActive?: Prisma.BoolFilter<"ServiceProviderCategory"> | boolean
  isInHome?: Prisma.BoolFilter<"ServiceProviderCategory"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ServiceProviderCategory"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ServiceProviderCategory"> | Date | string
}

export type ServiceProviderCategoryCreateManyParentInput = {
  id?: string
  name: string
  icon: string
  isActive?: boolean
  isInHome?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ServiceProviderCategoryUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.ServiceProviderCategoryUpdateManyWithoutParentNestedInput
}

export type ServiceProviderCategoryUncheckedUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.ServiceProviderCategoryUncheckedUpdateManyWithoutParentNestedInput
}

export type ServiceProviderCategoryUncheckedUpdateManyWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  icon?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isInHome?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ServiceProviderCategoryCountOutputType
 */

export type ServiceProviderCategoryCountOutputType = {
  children: number
}

export type ServiceProviderCategoryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  children?: boolean | ServiceProviderCategoryCountOutputTypeCountChildrenArgs
}

/**
 * ServiceProviderCategoryCountOutputType without action
 */
export type ServiceProviderCategoryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategoryCountOutputType
   */
  select?: Prisma.ServiceProviderCategoryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ServiceProviderCategoryCountOutputType without action
 */
export type ServiceProviderCategoryCountOutputTypeCountChildrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceProviderCategoryWhereInput
}


export type ServiceProviderCategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  icon?: boolean
  parentId?: boolean
  isActive?: boolean
  isInHome?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.ServiceProviderCategory$parentArgs<ExtArgs>
  children?: boolean | Prisma.ServiceProviderCategory$childrenArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceProviderCategoryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceProviderCategory"]>

export type ServiceProviderCategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  icon?: boolean
  parentId?: boolean
  isActive?: boolean
  isInHome?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.ServiceProviderCategory$parentArgs<ExtArgs>
}, ExtArgs["result"]["serviceProviderCategory"]>

export type ServiceProviderCategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  icon?: boolean
  parentId?: boolean
  isActive?: boolean
  isInHome?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.ServiceProviderCategory$parentArgs<ExtArgs>
}, ExtArgs["result"]["serviceProviderCategory"]>

export type ServiceProviderCategorySelectScalar = {
  id?: boolean
  name?: boolean
  icon?: boolean
  parentId?: boolean
  isActive?: boolean
  isInHome?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ServiceProviderCategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "icon" | "parentId" | "isActive" | "isInHome" | "createdAt" | "updatedAt", ExtArgs["result"]["serviceProviderCategory"]>
export type ServiceProviderCategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.ServiceProviderCategory$parentArgs<ExtArgs>
  children?: boolean | Prisma.ServiceProviderCategory$childrenArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceProviderCategoryCountOutputTypeDefaultArgs<ExtArgs>
}
export type ServiceProviderCategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.ServiceProviderCategory$parentArgs<ExtArgs>
}
export type ServiceProviderCategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.ServiceProviderCategory$parentArgs<ExtArgs>
}

export type $ServiceProviderCategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceProviderCategory"
  objects: {
    parent: Prisma.$ServiceProviderCategoryPayload<ExtArgs> | null
    children: Prisma.$ServiceProviderCategoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    icon: string
    parentId: string | null
    isActive: boolean
    isInHome: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["serviceProviderCategory"]>
  composites: {}
}

export type ServiceProviderCategoryGetPayload<S extends boolean | null | undefined | ServiceProviderCategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload, S>

export type ServiceProviderCategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceProviderCategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceProviderCategoryCountAggregateInputType | true
  }

export interface ServiceProviderCategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceProviderCategory'], meta: { name: 'ServiceProviderCategory' } }
  /**
   * Find zero or one ServiceProviderCategory that matches the filter.
   * @param {ServiceProviderCategoryFindUniqueArgs} args - Arguments to find a ServiceProviderCategory
   * @example
   * // Get one ServiceProviderCategory
   * const serviceProviderCategory = await prisma.serviceProviderCategory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceProviderCategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceProviderCategory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceProviderCategoryFindUniqueOrThrowArgs} args - Arguments to find a ServiceProviderCategory
   * @example
   * // Get one ServiceProviderCategory
   * const serviceProviderCategory = await prisma.serviceProviderCategory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceProviderCategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceProviderCategory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceProviderCategoryFindFirstArgs} args - Arguments to find a ServiceProviderCategory
   * @example
   * // Get one ServiceProviderCategory
   * const serviceProviderCategory = await prisma.serviceProviderCategory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceProviderCategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceProviderCategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceProviderCategory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceProviderCategoryFindFirstOrThrowArgs} args - Arguments to find a ServiceProviderCategory
   * @example
   * // Get one ServiceProviderCategory
   * const serviceProviderCategory = await prisma.serviceProviderCategory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceProviderCategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceProviderCategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceProviderCategories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceProviderCategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceProviderCategories
   * const serviceProviderCategories = await prisma.serviceProviderCategory.findMany()
   * 
   * // Get first 10 ServiceProviderCategories
   * const serviceProviderCategories = await prisma.serviceProviderCategory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceProviderCategoryWithIdOnly = await prisma.serviceProviderCategory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceProviderCategoryFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceProviderCategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceProviderCategory.
   * @param {ServiceProviderCategoryCreateArgs} args - Arguments to create a ServiceProviderCategory.
   * @example
   * // Create one ServiceProviderCategory
   * const ServiceProviderCategory = await prisma.serviceProviderCategory.create({
   *   data: {
   *     // ... data to create a ServiceProviderCategory
   *   }
   * })
   * 
   */
  create<T extends ServiceProviderCategoryCreateArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceProviderCategories.
   * @param {ServiceProviderCategoryCreateManyArgs} args - Arguments to create many ServiceProviderCategories.
   * @example
   * // Create many ServiceProviderCategories
   * const serviceProviderCategory = await prisma.serviceProviderCategory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceProviderCategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceProviderCategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceProviderCategories and returns the data saved in the database.
   * @param {ServiceProviderCategoryCreateManyAndReturnArgs} args - Arguments to create many ServiceProviderCategories.
   * @example
   * // Create many ServiceProviderCategories
   * const serviceProviderCategory = await prisma.serviceProviderCategory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceProviderCategories and only return the `id`
   * const serviceProviderCategoryWithIdOnly = await prisma.serviceProviderCategory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServiceProviderCategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServiceProviderCategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceProviderCategory.
   * @param {ServiceProviderCategoryDeleteArgs} args - Arguments to delete one ServiceProviderCategory.
   * @example
   * // Delete one ServiceProviderCategory
   * const ServiceProviderCategory = await prisma.serviceProviderCategory.delete({
   *   where: {
   *     // ... filter to delete one ServiceProviderCategory
   *   }
   * })
   * 
   */
  delete<T extends ServiceProviderCategoryDeleteArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceProviderCategory.
   * @param {ServiceProviderCategoryUpdateArgs} args - Arguments to update one ServiceProviderCategory.
   * @example
   * // Update one ServiceProviderCategory
   * const serviceProviderCategory = await prisma.serviceProviderCategory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceProviderCategoryUpdateArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceProviderCategories.
   * @param {ServiceProviderCategoryDeleteManyArgs} args - Arguments to filter ServiceProviderCategories to delete.
   * @example
   * // Delete a few ServiceProviderCategories
   * const { count } = await prisma.serviceProviderCategory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceProviderCategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceProviderCategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceProviderCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceProviderCategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceProviderCategories
   * const serviceProviderCategory = await prisma.serviceProviderCategory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceProviderCategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceProviderCategories and returns the data updated in the database.
   * @param {ServiceProviderCategoryUpdateManyAndReturnArgs} args - Arguments to update many ServiceProviderCategories.
   * @example
   * // Update many ServiceProviderCategories
   * const serviceProviderCategory = await prisma.serviceProviderCategory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceProviderCategories and only return the `id`
   * const serviceProviderCategoryWithIdOnly = await prisma.serviceProviderCategory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServiceProviderCategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceProviderCategory.
   * @param {ServiceProviderCategoryUpsertArgs} args - Arguments to update or create a ServiceProviderCategory.
   * @example
   * // Update or create a ServiceProviderCategory
   * const serviceProviderCategory = await prisma.serviceProviderCategory.upsert({
   *   create: {
   *     // ... data to create a ServiceProviderCategory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceProviderCategory we want to update
   *   }
   * })
   */
  upsert<T extends ServiceProviderCategoryUpsertArgs>(args: Prisma.SelectSubset<T, ServiceProviderCategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceProviderCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceProviderCategoryCountArgs} args - Arguments to filter ServiceProviderCategories to count.
   * @example
   * // Count the number of ServiceProviderCategories
   * const count = await prisma.serviceProviderCategory.count({
   *   where: {
   *     // ... the filter for the ServiceProviderCategories we want to count
   *   }
   * })
  **/
  count<T extends ServiceProviderCategoryCountArgs>(
    args?: Prisma.Subset<T, ServiceProviderCategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceProviderCategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceProviderCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceProviderCategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceProviderCategoryAggregateArgs>(args: Prisma.Subset<T, ServiceProviderCategoryAggregateArgs>): Prisma.PrismaPromise<GetServiceProviderCategoryAggregateType<T>>

  /**
   * Group by ServiceProviderCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceProviderCategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceProviderCategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceProviderCategoryGroupByArgs['orderBy'] }
      : { orderBy?: ServiceProviderCategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceProviderCategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceProviderCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceProviderCategory model
 */
readonly fields: ServiceProviderCategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceProviderCategory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceProviderCategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  parent<T extends Prisma.ServiceProviderCategory$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceProviderCategory$parentArgs<ExtArgs>>): Prisma.Prisma__ServiceProviderCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  children<T extends Prisma.ServiceProviderCategory$childrenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceProviderCategory$childrenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceProviderCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceProviderCategory model
 */
export interface ServiceProviderCategoryFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceProviderCategory", 'String'>
  readonly name: Prisma.FieldRef<"ServiceProviderCategory", 'String'>
  readonly icon: Prisma.FieldRef<"ServiceProviderCategory", 'String'>
  readonly parentId: Prisma.FieldRef<"ServiceProviderCategory", 'String'>
  readonly isActive: Prisma.FieldRef<"ServiceProviderCategory", 'Boolean'>
  readonly isInHome: Prisma.FieldRef<"ServiceProviderCategory", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ServiceProviderCategory", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ServiceProviderCategory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServiceProviderCategory findUnique
 */
export type ServiceProviderCategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ServiceProviderCategory to fetch.
   */
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
}

/**
 * ServiceProviderCategory findUniqueOrThrow
 */
export type ServiceProviderCategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ServiceProviderCategory to fetch.
   */
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
}

/**
 * ServiceProviderCategory findFirst
 */
export type ServiceProviderCategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ServiceProviderCategory to fetch.
   */
  where?: Prisma.ServiceProviderCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceProviderCategories to fetch.
   */
  orderBy?: Prisma.ServiceProviderCategoryOrderByWithRelationInput | Prisma.ServiceProviderCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceProviderCategories.
   */
  cursor?: Prisma.ServiceProviderCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceProviderCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceProviderCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceProviderCategories.
   */
  distinct?: Prisma.ServiceProviderCategoryScalarFieldEnum | Prisma.ServiceProviderCategoryScalarFieldEnum[]
}

/**
 * ServiceProviderCategory findFirstOrThrow
 */
export type ServiceProviderCategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ServiceProviderCategory to fetch.
   */
  where?: Prisma.ServiceProviderCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceProviderCategories to fetch.
   */
  orderBy?: Prisma.ServiceProviderCategoryOrderByWithRelationInput | Prisma.ServiceProviderCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceProviderCategories.
   */
  cursor?: Prisma.ServiceProviderCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceProviderCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceProviderCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceProviderCategories.
   */
  distinct?: Prisma.ServiceProviderCategoryScalarFieldEnum | Prisma.ServiceProviderCategoryScalarFieldEnum[]
}

/**
 * ServiceProviderCategory findMany
 */
export type ServiceProviderCategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * Filter, which ServiceProviderCategories to fetch.
   */
  where?: Prisma.ServiceProviderCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceProviderCategories to fetch.
   */
  orderBy?: Prisma.ServiceProviderCategoryOrderByWithRelationInput | Prisma.ServiceProviderCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceProviderCategories.
   */
  cursor?: Prisma.ServiceProviderCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceProviderCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceProviderCategories.
   */
  skip?: number
  distinct?: Prisma.ServiceProviderCategoryScalarFieldEnum | Prisma.ServiceProviderCategoryScalarFieldEnum[]
}

/**
 * ServiceProviderCategory create
 */
export type ServiceProviderCategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceProviderCategory.
   */
  data: Prisma.XOR<Prisma.ServiceProviderCategoryCreateInput, Prisma.ServiceProviderCategoryUncheckedCreateInput>
}

/**
 * ServiceProviderCategory createMany
 */
export type ServiceProviderCategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceProviderCategories.
   */
  data: Prisma.ServiceProviderCategoryCreateManyInput | Prisma.ServiceProviderCategoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceProviderCategory createManyAndReturn
 */
export type ServiceProviderCategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * The data used to create many ServiceProviderCategories.
   */
  data: Prisma.ServiceProviderCategoryCreateManyInput | Prisma.ServiceProviderCategoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceProviderCategory update
 */
export type ServiceProviderCategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceProviderCategory.
   */
  data: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateInput, Prisma.ServiceProviderCategoryUncheckedUpdateInput>
  /**
   * Choose, which ServiceProviderCategory to update.
   */
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
}

/**
 * ServiceProviderCategory updateMany
 */
export type ServiceProviderCategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceProviderCategories.
   */
  data: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateManyMutationInput, Prisma.ServiceProviderCategoryUncheckedUpdateManyInput>
  /**
   * Filter which ServiceProviderCategories to update
   */
  where?: Prisma.ServiceProviderCategoryWhereInput
  /**
   * Limit how many ServiceProviderCategories to update.
   */
  limit?: number
}

/**
 * ServiceProviderCategory updateManyAndReturn
 */
export type ServiceProviderCategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * The data used to update ServiceProviderCategories.
   */
  data: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateManyMutationInput, Prisma.ServiceProviderCategoryUncheckedUpdateManyInput>
  /**
   * Filter which ServiceProviderCategories to update
   */
  where?: Prisma.ServiceProviderCategoryWhereInput
  /**
   * Limit how many ServiceProviderCategories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceProviderCategory upsert
 */
export type ServiceProviderCategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceProviderCategory to update in case it exists.
   */
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
  /**
   * In case the ServiceProviderCategory found by the `where` argument doesn't exist, create a new ServiceProviderCategory with this data.
   */
  create: Prisma.XOR<Prisma.ServiceProviderCategoryCreateInput, Prisma.ServiceProviderCategoryUncheckedCreateInput>
  /**
   * In case the ServiceProviderCategory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceProviderCategoryUpdateInput, Prisma.ServiceProviderCategoryUncheckedUpdateInput>
}

/**
 * ServiceProviderCategory delete
 */
export type ServiceProviderCategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  /**
   * Filter which ServiceProviderCategory to delete.
   */
  where: Prisma.ServiceProviderCategoryWhereUniqueInput
}

/**
 * ServiceProviderCategory deleteMany
 */
export type ServiceProviderCategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceProviderCategories to delete
   */
  where?: Prisma.ServiceProviderCategoryWhereInput
  /**
   * Limit how many ServiceProviderCategories to delete.
   */
  limit?: number
}

/**
 * ServiceProviderCategory.parent
 */
export type ServiceProviderCategory$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  where?: Prisma.ServiceProviderCategoryWhereInput
}

/**
 * ServiceProviderCategory.children
 */
export type ServiceProviderCategory$childrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
  where?: Prisma.ServiceProviderCategoryWhereInput
  orderBy?: Prisma.ServiceProviderCategoryOrderByWithRelationInput | Prisma.ServiceProviderCategoryOrderByWithRelationInput[]
  cursor?: Prisma.ServiceProviderCategoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServiceProviderCategoryScalarFieldEnum | Prisma.ServiceProviderCategoryScalarFieldEnum[]
}

/**
 * ServiceProviderCategory without action
 */
export type ServiceProviderCategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceProviderCategory
   */
  select?: Prisma.ServiceProviderCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceProviderCategory
   */
  omit?: Prisma.ServiceProviderCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceProviderCategoryInclude<ExtArgs> | null
}
